from typing import List, Optional
import uuid

from pydantic import BaseModel, Field


class MinimalSource(BaseModel):
    """Represents a specific chunk or text segment retrieved from a file."""

    file_path: str
    first_character_index: int
    last_character_index: int
    content: Optional[str] = None


class UnansweredQuestion(BaseModel):
    """Defines an evaluation question that has not yet been processed."""

    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """A question that includes ground-truth sources and its target answer."""

    sources: List[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """A collection of ground-truth test questions used for RAG evaluation."""

    rag_questions: List[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """The search outcome for a single question containing matched sources."""

    question_id: str
    question_str: str
    retrieved_sources: List[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """A search outcome combined with the text answer generated by the LLM."""

    answer: str


class StudentSearchResults(BaseModel):
    """A complete batch of search results generated by a pipeline run."""

    search_results: List[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(StudentSearchResults):
    """A complete batch of both retrieved sources and generated answers."""

    search_results: List[MinimalAnswer]  # type: ignore[assignment]
